# Indexación y slicing en arrays NumPy:

Puedes acceder a elementos individuales de un array NumPy utilizando la indexación, y también puedes realizar #slicing" para seleccionar subconjuntos de elementos.

Ejemplo de indexación y slicing en un array NumPy

In [ ]:
# Indexación
import numpy as np

array3 = np.array([0,1,2,3,4,6,7])
print("Mi elemento en la posición 1:", array3[1])

Mi elemento en la posición 1: 1


In [ ]:
# slicing
sub_array = array3[2:8] # Rango de posiciones
sub_array

array([2, 3, 4, 6, 7])

# Ejemplos de operaciones matriciales con NumPy:

NumPy es especialmente poderoso cuando se trata de operaciones matriciales. Puedes realizar multiplicación de matrices, transposición, cálculos de determinantes y mucho más de manera efiente.

Ejemplo de multiplicación de matrices con NumPy:

In [ ]:
matriz1 = np.array([[1,2],[3,4]])
matriz1

array([[1, 2],
       [3, 4]])

In [ ]:
matriz2 = np.array([[5,6],[7,8]])
matriz2

array([[5, 6],
       [7, 8]])

In [ ]:
resultado = np.dot(matriz1,matriz2)
resultado

array([[19, 22],
       [43, 50]])

# Problema: Cálculo de Estadística en Datos de Ventas

Supongamos ue tienes un conjunto de datos de ventas de productos en una tienda durante varios meses. Cada fila del conjunto de datos representa una venta y contiene información sobre el producto vendido, la cantidad vendida y el precio unitario. Tu objetivo es realizar algunas estadísticas básicas con estos datos utilizando NumPy.

In [ ]:
# datos de venta (producto, cantidad, precio unitario)

ventas = np.array([
    ["Shampoo",       100,  24000],
    ["Acondicionador", 50,  13000],
    ["Jabón",          75,  6000 ],
    ["Crema de manos", 120, 18000],
    ["Protector solar", 60, 82000]
])

# Calcular el total de ventas para cada producto

total_ventas = ventas[:,1].astype(float)* ventas[:,2].astype(float)
print(total_ventas)

# Calcular el total de ventas en general
total_ventas_general = np.sum(total_ventas)
print(total_ventas_general)

# Calcular el producto más vendido
producto_mas_vendida = ventas[np.argmax(ventas[:,1].astype(int)),0]
print(producto_mas_vendida)

# Calcular el producto menos vendido
producto_menos_vendido = ventas[np.argmin(ventas[:,1].astype(int)),0]
print(producto_menos_vendido)

# Calcular valor promedio por producto
precio_promedio_por_productos = np.mean(ventas[:,2].astype(float))
print(precio_promedio_por_productos)

# Calcular el valor que corresponde a la madiana del precio del producto
mediana_precio_producto = np.median(ventas[:,2].astype(float))
print(mediana_precio_producto)

[2400000.  650000.  450000. 2160000. 4920000.]
10580000.0
Crema de manos
Acondicionador
28600.0
18000.0
