# Introducción a NumPy

NumPy (Numerical Python) es una librería de Python que se utiliza ampliamente en el procesamiento numércio y científico de datos. Proporciona una estructura de datos llamada 'array' (arreglos) que es eficiente en términos de almacenamiento y cómputo, y ofrece una amplia gama de funciones para trabajar con estos arreglos. A continuación, exploraremos los conceptos clave relacionados con NumPy.

**¿Qué es NumPy?**

NumPy es una librería de código abierto en Python que se utiliza para realizar operaciones matemáticas y lógicas en arreglos multidimensionales o matrices. Está diseñada para trabajar con datos numércios y es ampliamnete utilizada en el ámbito de la ciencia de datos, ingeniería y la computación científica debido a su eficiencia y facilidad de uso


**Creación de arrays NumPy**

NumPy permite crear arrays multidimensionales de manera eficiente. Puedes crear arrays NumPy utilizando listas de Python o mediante funciones específicas de NumPy.

Ejemplo de creación de un array NumPy.

In [ ]:
lista = [2,5,9,7,3,4,6]
lista

[2, 5, 9, 7, 3, 4, 6]

In [ ]:
import numpy as np
# Crear un arreglo
mi_array = np.array([2,5,9,7,3,4,6])
print(mi_array)

[2 5 9 7 3 4 6]


# Operaciones básicas con arrays NumPy:

NumPy proporcina numerosas operaciones matemáticas y aritm´ticas que se pueden realizar en arrys, incluyendo sume, resta, multiplicación y división, tanto elemento por elemento como a nivel de matriz

Ejemplo de operaciones básicas con arrays NumPy

In [ ]:
lista*2

[2, 5, 9, 7, 3, 4, 6, 2, 5, 9, 7, 3, 4, 6]

In [ ]:
mi_array*2

array([ 4, 10, 18, 14,  6,  8, 12])

In [ ]:
# Suma de arreglos

array1 = np.array([1,2,3])
array2 = np.array([9,8,7])

lista = [9,8,7]

#suma = array1 + array2

suma = array1 + lista

print(suma)
type(suma)

[10 10 10]


numpy.ndarray

In [ ]:
producto = array1 * array2
producto

array([ 9, 16, 21])